services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  web:
    build: ./app
    container_name: flask-container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
